global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'secureops-backend'
    static_configs:
      - targets: ['backend:8010']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'secureops-frontend'
    static_configs:
      - targets: ['frontend:3010']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']