global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'secureops-backend'
    static_configs:
      - targets: ['backend:8000']
  - job_name: 'secureops-app'
    static_configs:
      - targets: ['app:8000']
  - job_name: 'secureops-celery-worker'
    static_configs:
      - targets: ['celery-worker:5555']
  - job_name: 'secureops-celery-beat'
    static_configs:
      - targets: ['celery-beat:5556']
  - job_name: 'secureops-frontend'
    static_configs:
      - targets: ['frontend:80']
